const summary = [
    {
      date: '27 Sep',
      'Weight kgs': 123,
      'Height': 183,
      'Bicep (Right)': 10,
      'Neck': 12,
      'Waist (Small)': 36,
      'Waist (Belly button)': 100,
      'Hips': 40,
      'Glutes': 20,
      'Thigh': 33,
      'Total cm': 830,
      'Temperature C': 36.5,
      'Pulse bpm': 130
    },{
      date: '23 Sep',
      'Weight kgs': 123,
      'Height': 183,
      'Bicep (Right)': 10,
      'Neck': 12,
      'Waist (Small)': 36,
      'Waist (Belly button)': 100,
      'Hips': 40,
      'Glutes': 20,
      'Thigh': 33,
      'Total cm': 830,
      'Temperature C': 36.5,
      'Pulse bpm': 130
    },{
      date: '20 Sep',
      'Weight kgs': 123,
      'Height': 183,
      'Bicep (Right)': 10,
      'Neck': 12,
      'Waist (Small)': 36,
      'Waist (Belly button)': 100,
      'Hips': 40,
      'Glutes': 20,
      'Thigh': 33,
      'Total cm': 830,
      'Temperature C': 36.5,
      'Pulse bpm': 130
    },{
      date: '17 Sep',
      'Weight kgs': 123,
      'Height': 183,
      'Bicep (Right)': 10,
      'Neck': 12,
      'Waist (Small)': 36,
      'Waist (Belly button)': 100,
      'Hips': 40,
      'Glutes': 20,
      'Thigh': 33,
      'Total cm': 830,
      'Temperature C': 36.5,
      'Pulse bpm': 130
    },{
      date: '13 Sep',
      'Weight kgs': 123,
      'Height': 183,
      'Bicep (Right)': 10,
      'Neck': 12,
      'Waist (Small)': 36,
      'Waist (Belly button)': 100,
      'Hips': 40,
      'Glutes': 20,
      'Thigh': 33,
      'Total cm': 830,
      'Temperature C': 36.5,
      'Pulse bpm': 130
    },{
      date: '10 Sep',
      'Weight kgs': 123,
      'Height': 183,
      'Bicep (Right)': 10,
      'Neck': 12,
      'Waist (Small)': 36,
      'Waist (Belly button)': 100,
      'Hips': 40,
      'Glutes': 20,
      'Thigh': 33,
      'Total cm': 830,
      'Temperature C': 36.5,
      'Pulse bpm': 130
    },
  ]
  
  export { summary }